### PR TITLE
make jBCrypt an OSGI bundle

### PR DESCRIPTION
**Pull request by gdelafosse**
I need to use JBCrypt in an OSGI container.
Would you accept this request to make it a valid OSGI bundle?

### CODE REVIEW

**Comment by svenkubiak** [comment]
Changing the packaging in pom.xml would result in making the the artifact not available more as jar if used as a dependency, wouldn't it?

**Comment by gdelafosse** [comment]
No, it will still be a jar usable in a classic java environment. The maven-bundle-plugin just adds some entries into the MANIFEST that tells wich packages are exposed publicly for the others in an OSGI container.

**Comment by svenkubiak** [comment]
Ok. I'll need to checks this. If this JAR bulding isn't touched and workes as before, I see no problem in merging the PR.

**Comment by svenkubiak** [comment]
Ok. Looks good to me. I'll added the bundling feature manually in version 0.4.1. Should be on maven central soon.

Cheers,
Sven

**Comment by gdelafosse** [comment]
Thanks,
just for information, why didn't you merge my branch instead of reporting manually?

**Comment by svenkubiak** [comment]
I was editing some other stuff and the changes where that small, that i just changed it ;-)

**Comment by gdelafosse** [comment]
ok, so I delete my branch
thanks for having accepted this request

**Pull request closed without merging**
